name: Check and test the source code

on:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Check the source code
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Install SFML
      run: |
        sudo apt-get update
        sudo apt-get install libsfml-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
